
defaults: &defaults
  working_directory: ~/react-rnd
  docker:
    - image: bokuweb/node-go-with-browser:latest
      environment:
        DISPLAY: ":99"

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Lint
          command: yarn run lint && yarn run tsc
      - run:
          name: Test
          command: |
            xvfbd start
            yarn run test
            xvfbd stop    
  deploy:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - add-ssh-keys:
          fingerprints:
            - "9e:ff:cc:c5:e1:e4:6a:e9:c2:bb:65:d9:f3:b5:4d:be"
      - run:
          name: Setup git
          command: |
            git config --global user.email "bokuweb12@gmail.com"
            git config --global user.name "bokuweb"          
      - run:
          name: Deploy
          filters:
            branches:
              only: master
          command: yarn run deploy                   
  patch_release:
    <<: *defaults
    steps:
      - add-ssh-keys:
          fingerprints:
            - "9e:ff:cc:c5:e1:e4:6a:e9:c2:bb:65:d9:f3:b5:4d:be"          
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Build
          command: yarn run build
      - run:
          name: Setup git
          command: |
            git config --global user.email "bokuweb12@gmail.com"
            git config --global user.name "bokuweb"
      - run:
          name: Login npm
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ~/.npmrc
            npm whoami
      - run:
          name: Publish to npm
          command: |
            sh scripts/deploy-patch.sh
  minor_release:
    <<: *defaults
    steps:
      - add-ssh-keys:
          fingerprints:
            - "9e:ff:cc:c5:e1:e4:6a:e9:c2:bb:65:d9:f3:b5:4d:be"
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Build
          command: yarn run build          
      - run:
          name: Setup git
          command: |
            git config --global user.email "bokuweb12@gmail.com"
            git config --global user.name "bokuweb"
      - run:
          name: Login npm
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ~/.npmrc
            npm whoami
      - run:
          name: Publish to npm
          command: |
            sh scripts/deploy-minor.sh
workflows:
  version: 2
  build_pipeline:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only: master
      - confirm_patch:
          type: approval
          filters:
            branches:
              only: master
          requires:
            - build
      - confirm_minor:
          type: approval
          filters:
            branches:
              only: master
          requires:
            - build
      - patch_release:
          filters:
            branches:
              only: master
          requires:
            - confirm_patch
      - minor_release:
          filters:
            branches:
              only: master
          requires:
            - confirm_minor
